name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: setup1
      run: mkdir build/
    - name: setup2
      run: cp -r assets/ build/assets/
    - name: make release
      run: make release
